# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c77622689f6c11e486a4d6fe7555f682ae64917d7c579788ce7adc05389760bd7980e4a5da5fe12b9d3d0f446ae5c9647fe0adfb6de8d2e419c8a69a18be8f

test:
  secret_key_base: 01c0479bb9e9793533950ee47184107734ed4ef4211b63c89e1df0e69e3ce2bc67b592f8f5d3a649a10ee6db9e228156fb422474623c4af74d9834db106248fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
