# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a61bb52c34f343f9fd87f9f07be93e01cf2834af184b57e9c15532691eff25fe92eeba632d7d83cc9e915e2cf9098936628454c412e9a9dd475aced482a26d4

test:
  secret_key_base: 5946ca60b49591618065d03bf58425e366e81c505156abb0b470c764dfa91bc4298161455728934877d803014ede2cdc5dd5bdb10544d8d32aa6ef5b62b21b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
